# Natural Language to SQL Query App Configuration

[aws.bedrock]
# AWS Bedrock Configuration
access_key_id = "AKIA..."
secret_access_key = "your_secret_key"
region = "us-east-1"
model_id = "anthropic.claude-3-5-sonnet-20240620-v1:0"

[snowflake]
# Snowflake Configuration  
user = "database_user"
password = "password_to_login"
account = "account_name.region"
warehouse = "warehouse_to_use"
database = "database_name"
schema = "schema_name"

# Connection settings
connection_timeout = 60
login_timeout = 30

[application]
# Application Configuration
title = "Natural Language to SQL Query App"
max_rows = 1000
log_level = "INFO"

# Performance settings
query_timeout = 300  # seconds
max_query_history = 100

[security]
# Security settings
enable_query_logging = true
enable_error_tracking = true
enable_debug_mode = false

[ui]
# Streamlit UI Configuration
server_port = 8501
server_address = "localhost"
browser_gather_usage_stats = false

# Theme and display settings
theme = "light"  # Options: light, dark, auto
show_query_suggestions = true
default_chart_type = "auto"  # Options: auto, bar, line, scatter
show_debug_info = false

[features]
# Feature flags
enable_sql_preview = true
enable_performance_monitoring = true
enable_usage_analytics = false
enable_schema_cache = true
enable_query_explain = false
enable_auto_refresh = true

# Cache settings
cache_expiry_minutes = 300

[logging]
# Logging configuration
file_path = "app.log"
rotation_size = "10MB"
retention_days = 30
format = "standard"  # Options: standard, detailed, json 